services:
  db:
    image: postgres:15.15
    restart: always
    volumes:
      - postgre-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"



volumes:
  postgre-data:
    driver: local